<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="MimeKit" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\ACPoller.Abstractions\ACPoller.Abstractions.csproj" />
  </ItemGroup>

</Project>
